SELECT DISTINCT c.CART_ID
FROM CART_PRODUCTS c
JOIN (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) y ON y.CART_ID = c.CART_ID
JOIN (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) m ON m.CART_ID = c.CART_ID
ORDER BY CART_ID ASC;