-- 코드를 입력하세요
SELECT
    p.PRODUCT_CODE,
    SUM(p.PRICE * o.AMOUNT) AS SALES
FROM PRODUCT p
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) o ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC;