SELECT
    ID,
    CASE 
        WHEN Q = 1 THEN 'CRITICAL'
        WHEN Q = 2 THEN 'HIGH'
        WHEN Q = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS Q
    FROM ECOLI_DATA
) AS SUB
ORDER BY ID ASC;

/*
SELECT
    ID,
    CASE 
        WHEN P_RANK / TOTAL_COUNT <= 0.25 THEN 'CRITICAL'
        WHEN P_RANK / TOTAL_COUNT <= 0.50 THEN 'HIGH'
        WHEN P_RANK / TOTAL_COUNT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT
        ID,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS P_RANK,
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM ECOLI_DATA
) AS SUB
ORDER BY ID ASC;
*/