-- 코드를 입력하세요
SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) AS MONTH, u.GENDER, COUNT(DISTINCT o.USER_ID) AS USERS
FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER;

/*
SELECT 
    YEAR(SALES_DATE) as YEAR,
    MONTH(SALES_DATE) as MONTH,
    GENDER,
    COUNT(DISTINCT o.USER_ID) as USERS
FROM ONLINE_SALE o
JOIN USER_INFO u ON o.USER_ID = u.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER;
*/