WITH USERS_2021 AS (
    -- 2021년 가입자 수 계산
    SELECT COUNT(*) as total_users
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
MONTHLY_PURCHASES AS (
    -- 2021년 가입자들의 월별 구매 현황
    SELECT 
        YEAR(s.SALES_DATE) as YEAR,
        MONTH(s.SALES_DATE) as MONTH,
        COUNT(DISTINCT s.USER_ID) as PURCHASED_USERS
    FROM ONLINE_SALE s
    JOIN USER_INFO u ON s.USER_ID = u.USER_ID
    WHERE YEAR(u.JOINED) = 2021
    GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE)
)
SELECT 
    YEAR,
    MONTH,
    PURCHASED_USERS,
    ROUND(PURCHASED_USERS / total_users, 1) as PUCHASED_RATIO
FROM MONTHLY_PURCHASES
CROSS JOIN USERS_2021
ORDER BY YEAR, MONTH;