-- 코드를 입력하세요
SELECT
    HISTORY_ID,
    FLOOR(
        DAILY_FEE * 대여일수 * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100
    ) AS FEE
FROM (
    SELECT
        h.HISTORY_ID,
        c.DAILY_FEE,
        c.CAR_TYPE,
        DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS 대여일수,
        CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
) base
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON base.CAR_TYPE = d.CAR_TYPE
    AND base.DURATION_TYPE = d.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;