WITH RECURSIVE time AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1 FROM time WHERE HOUR < 23
)
SELECT 
    t.HOUR,
    COUNT(ANIMAL_ID) as COUNT
FROM time t
LEFT JOIN ANIMAL_OUTS ON t.HOUR = HOUR(DATETIME)
GROUP BY t.HOUR
ORDER BY t.HOUR;