SELECT
    ii.ITEM_ID,
    ii.ITEM_NAME,
    ii.RARITY
FROM ITEM_TREE t
JOIN(
    SELECT
        ITEM_ID,
        ITEM_NAME,
        RARITY
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
) i ON i.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO ii ON ii.ITEM_ID = t.ITEM_ID
ORDER BY ITEM_ID DESC;